name: Carbon Intensity ETL

on:
  schedule:
    # Runs ETL every hour
    - cron: "0 * * * *"
    # Runs cleanup daily at 02:00 UTC
    - cron: "0 2 * * *"
  workflow_dispatch:  # Allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL or Cleanup
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          if [ "$(date +%H)" = "02" ]; then
            echo "Running cleanup job..."
            python etl.py --cleanup-only
          else
            echo "Running ETL job..."
            python etl.py
          fi
